# Rules of the grammar
R = {
    "K": [
        ["S", "P"], ["X", "O"], ["X", "Pel"], ["X", "Ket"], ["X", "Y"], ["X", "Z"], ["X", "A"]
    ],
    "S": [
        ["Hitam"], ["Rindang"], ["Kontemporer"], ["Siti"], ["Rahayu"], ["Adi"], ["Santoso"], ["Ratna"], ["Kopi"], ["Denpasar"], 
        ["Kiki"], ["Prof"], ["Dr"], ["Hadi"], ["Prayitno"], ["Bali"], ["Jakarta"], ["Haryono"], ["Bogor"], ["Bandung"], ["Monas"], 
        ["Copacabana"], ["Rio"], ["de"], ["Janeiro"], ["Baikal"], ["Sinta"], ["Mediterania"], ["Bukit"], ["Tinggi"], ["Danau"], ["Baikal"], 
        ["Jawa"], ["Timur"], ["Saka"], ["Arab"], ["Saudi"], ["Indonesia"], ["Koi"], ["Jepang"], ["Medan"],
        
        ["Para"], ["Itu"], ["Tersebut"], ["Dari"], ["Saya"], ["Kita"], ["Itu"], ["Ini"], ["Yang"], ["Bahasa"], ["Saya"], ["Dia"],

        
        ["Nenek"], ["Polisi"], ["Ibu"], ["Daun"], ["Ubi"], ["Acara"], ["Orang"], ["Pemadam"], ["Kebakaran"], ["Waktu"], ["Penduduk"], ["Desa"], ["Anak"], ["Laki-laki"],
        ["Makanan"], ["Siswa"], ["Taman"], ["Kota"], ["Perpustakaan"], ["Kampus"], ["Jalan"], ["Wahana"], ["Burung"], ["Merpati"],
        ["Siang"], ["Hari"], ["Kolam"], ["Kuda"], ["Lintasan"], ["Pacu"], ["Monyet"], ["Ranting"], ["Pohon"], ["Kelinci"], ["Kebun"],
        ["Lumba-lumba"], ["Bunga"], ["Padang"], ["Rumput"], ["Lebah"], ["Buaya"], ["Tepi"], ["Danau"], ["Mahasiswa"], ["Acara"], ["Seminar"],
        ["Kakek"], ["Kursi"], ["Rotan"], ["Pelatih"], ["Orang"], ["Rencana"], ["Perjalanan"], ["Pengembangan"], ["Teknologi"], ["Gadis"],
        ["Kecil"], ["Boneka"], ["Air"], ["Terjun"], ["Pegunungan"], ["Pertunjukan"], ["Seni"], ["Malam"], ["Sejarah"], ["Mekar"], ["Tua"],
        ["Rasa"], ["Cokelat"], ["Taman"], ["Kucing"], ["Teman"], ["Anak-Anak"], ["Udara"], ["Kesejukan"], ["Kesegaran"], ["Pikiran"], ["Prestasi"],
        ["Pohon"], ["Air"], ["Hujan"], ["Suasana"], ["Romantis"], ["Cita-cita"], ["Kesuksesan"], ["Hewan"], ["Peliharaan"], ["Pameran"],
        ["Karya"], ["Budaya"], ["Lokal"], ["Wisata"], ["Daerah"], ["Arab"], ["Kuliah"], ["Pentas"], ["Universitas"], ["Ogoh-ogoh"], ["Negara"],
        ["Penghasil"], ["Minyak"], ["Tahun"], ["Baru"], ["Saka"], ["Dunia"], ["Negara"], ["Pantai"], ["Bu"], ["Warung"], ["Hari"], ["Budaya"],
        ["Juara"], ["Lomba"], ["Tengah"], ["Bapak"], ["Hujan"], ["Tetangga"], ["Keindahan"], ["Pantainya"], ["Tetangga"], ["Bukit"], ["Pemandangan"],
        ["Alam"], ["Pantai"], ["Kota"], ["Danau"], ["Laut"], ["Kulinernya"], ["Bukit"], ["Tinggi"], ["Proyek"], ["Bidang"], ["Ekologi"], ["Seminar"],
        ["Dunia"], ["Keindahan"], ["Pantainya"], ["Kota"], ["Kulinernya"], ["Hujan"], ["Tengah"], ["Budaya"], ["Malam"], ["Hari"], ["Pentas"],
        ["Ogoh-ogoh"], ["Tahun"], ["Penghasil"], ["Minyak"], ["Kegiatan"], ["Pengabdian"], ["Ketertiban"], ["Ikan"], ["Kupu-kupu"], ["Sapi"], ["Nektar"],
        ["Kepulauan"], ["Pasang"], ["Sepatu"], ["Rak"], ["Buah"], ["Rumah"], ["Tahap"], ["Konstruksi"], ["Ekor"], ["Belakang"], ["Pengunjung"], ["Kamar"], ["Tidur"],
        ["Teater"], ["Mobil"], ["Kotak"], ["Mainan"], ["Buku"], ["Bungkus"], ["Rokok"], ["Kebudayaan"], ["Asrama"], ["Putri"], ["Pemain"], ["Sepak"], ["Bola"], ["Guru"], ["Tari"],

        ["NP", "Noun"],
        ["NP", "Verb"],
        ["NP", "NumP"],
        ["NP", "AdjP"],
        ["NP", "PropNoun"],
        ["NP", "Pronoun"],
        ["Banyak"], ["Lima"], ["Sedikit"], ["Seekor"], ["Dua"], ["Lima"], ["Belas"], ["Tiga"], ["Tujuh"], ["Puluh"], ["Sepuluh"], ["Dua"], ["Delapan"],
        ["NumP", "NP"]
    ],
    "P": [
        ["Menaiki"], ["Mempunyai"], ["Bermain"], ["Belajar"], ["Menjaga"], ["Terbang"], ["Berenang"], ["Pacuan"], ["Berlari"], 
        ["Bergelantungan"], ["Hinggap"], ["Mengunyah"], ["Berjemur"], ["Menjadi"], ["Menyukai"], ["Disusun"], ["Berlangsung"], ["Menghibur"], 
        ["Menjadi"], ["Memberikan"], ["Membuat"], ["Menampilkan"], ["Tarik"], ["Berlibur"], ["Merupakan"], ["Tersebut"], ["Menyanyi"], 
        ["Membantu"], ["Terpajang"], ["Adalah"], ["Luas"], ["Kursus"], ["Meneliti"], ["Orang"], ["Membeli"], ["Berlari"], ["Banyak"], 
        ["Disiram"], ["Lama"], ["Indah"], ["Nyaman"], ["Dalam"], ["Belajar"], ["Bermain"], ["Dalam"], ["Menyukai"], ["Disusun"], 
        ["Berlangsung"], ["Menghibur"], ["Menjadi"], ["Memberikan"], ["Membuat"], ["Menampilkan"], ["Tarik"], ["Merupakan"], ["Memberikan"], 
        ["Dilakukan"], ["Sedang"], ["Berlibur"], ["Merupakan"], ["Menyambut"], ["Merupakan"], ["Memiliki"], ["Terletak"], ["Menyanyi"], 
        ["Membantu"], ["Dikenal"], ["Terkenal"], ["Membantu"], ["Menjadi"], ["Terkenal"], ["Adalah"], ["Terdalam"], ["Terkenal"], ["Dikenal"], 
        ["Terletak"], ["Menyambut"], ["Terpajang"], ["Mengambil"], ["Menghadiri"], ["Mengikuti"], ["Diperbolehkan"], ["Menyelamatkan"], ["Memasak"],
        ["Melompat-lompat"], ["Mengumpulkan"],
        ["Verb", "NP"],
        ["Verb", "AdjP"],
        ["Adv", "VP"],
        ["Dewasa"], ["Jarang"], ["Lezat"], ["Sering"], ["Banyak"], ["Cepat"], ["Kecil"], ["Putih"], ["Lepas"], ["Baik"], ["Pesat"], ["Senang"], ["Barunya"], ["Indah"], 
        ["Panjang"], ["Kelemahannya"], ["Terbesar"], ["Kebanggaan"], ["Setia"], ["Sejuk"], ["Tinggi"], ["Pendorong"], ["Manis"], ["Daya"], 
        ["Indah"], ["Baik"], ["Pesat"], ["Senang"], ["Barunya"], ["Indah"], ["Panjang"], ["Kelemahannya"], ["Kebanggaan"], ["Setia"], ["Sejuk"], 
        ["Tinggi"], ["Pendorong"], ["Manis"], ["Daya"], ["Terbesar"], ["Pemilik"], ["Ramai"], ["Selalu"], ["Indah"], ["Ikon"], ["Terdalam"], 
        ["Pemimpin"], ["Pakar"], ["Pembicara"], ["Indah"], ["Ramai"], ["Terbesar"], ["Baru"], ["Digunakan"], ["Pagi"], ["Besar"],
        ["Adv", "AdjP"],
        ["AdjP", "Adv"],
        # ["AdjP", "VP"],
        ["Verb", "VP"],
        ["NumP", "NP"],
        ["AdjP", "NP"], ["Banyak"], ["Lima"], ["Sedikit"], ["Seekor"], ["Dua"], ["Lima"], ["Belas"], ["Tiga"], ["Tujuh"], ["Puluh"], ["Sepuluh"], ["Dua"], ["Delapan"]
    ],
    "O":[
        ["Nenek"], ["Polisi"], ["Ibu"], ["Daun"], ["Ubi"], ["Acara"], ["Orang"], ["Pemadam"], ["Kebakaran"], ["Waktu"], ["Penduduk"], ["Desa"], ["Anak"], ["Laki-laki"],
        ["Makanan"], ["Siswa"], ["Taman"], ["Kota"], ["Perpustakaan"], ["Kampus"], ["Jalan"], ["Wahana"], ["Burung"], ["Merpati"],
        ["Siang"], ["Hari"], ["Kolam"], ["Kuda"], ["Lintasan"], ["Pacu"], ["Monyet"], ["Ranting"], ["Pohon"], ["Kelinci"], ["Kebun"],
        ["Lumba-lumba"], ["Bunga"], ["Padang"], ["Rumput"], ["Lebah"], ["Buaya"], ["Tepi"], ["Danau"], ["Mahasiswa"], ["Acara"], ["Seminar"],
        ["Kakek"], ["Kursi"], ["Rotan"], ["Pelatih"], ["Orang"], ["Rencana"], ["Perjalanan"], ["Pengembangan"], ["Teknologi"], ["Gadis"],
        ["Kecil"], ["Boneka"], ["Air"], ["Terjun"], ["Pegunungan"], ["Pertunjukan"], ["Seni"], ["Malam"], ["Sejarah"], ["Mekar"], ["Tua"],
        ["Rasa"], ["Cokelat"], ["Taman"], ["Kucing"], ["Teman"], ["Anak-Anak"], ["Udara"], ["Kesejukan"], ["Kesegaran"], ["Pikiran"], ["Prestasi"],
        ["Pohon"], ["Air"], ["Hujan"], ["Suasana"], ["Romantis"], ["Cita-cita"], ["Kesuksesan"], ["Hewan"], ["Peliharaan"], ["Pameran"],
        ["Karya"], ["Budaya"], ["Lokal"], ["Wisata"], ["Daerah"], ["Arab"], ["Kuliah"], ["Pentas"], ["Universitas"], ["Ogoh-ogoh"], ["Negara"],
        ["Penghasil"], ["Minyak"], ["Tahun"], ["Baru"], ["Saka"], ["Dunia"], ["Negara"], ["Pantai"], ["Bu"], ["Warung"], ["Hari"], ["Budaya"],
        ["Juara"], ["Lomba"], ["Tengah"], ["Bapak"], ["Hujan"], ["Tetangga"], ["Keindahan"], ["Pantainya"], ["Tetangga"], ["Bukit"], ["Pemandangan"],
        ["Alam"], ["Pantai"], ["Kota"], ["Danau"], ["Laut"], ["Kulinernya"], ["Bukit"], ["Tinggi"], ["Proyek"], ["Bidang"], ["Ekologi"], ["Seminar"],
        ["Dunia"], ["Keindahan"], ["Pantainya"], ["Kota"], ["Kulinernya"], ["Hujan"], ["Tengah"], ["Budaya"], ["Malam"], ["Hari"], ["Pentas"],
        ["Ogoh-ogoh"], ["Tahun"], ["Penghasil"], ["Minyak"], ["Kegiatan"], ["Pengabdian"], ["Ketertiban"], ["Ikan"], ["Kupu-kupu"], ["Sapi"], ["Nektar"],
        ["Kepulauan"], ["Pasang"], ["Sepatu"], ["Rak"], ["Buah"], ["Rumah"], ["Tahap"], ["Konstruksi"], ["Ekor"], ["Belakang"], ["Pengunjung"], ["Kamar"], ["Tidur"],
        ["Teater"], ["Mobil"], ["Kotak"], ["Mainan"], ["Buku"], ["Bungkus"], ["Rokok"], ["Kebudayaan"], ["Asrama"], ["Putri"], ["Pemain"], ["Sepak"], ["Bola"], ["Guru"], ["Tari"],

        ["NP", "PropNoun"],
        ["NP", "Verb"],
        ["NP", "NumP"],
        ["NP", "AdjP"],
        ["NP", "PropNoun"],
        ["NP", "Pronoun"],
        ["Dewasa"], ["Jarang"], ["Lezat"], ["Sering"], ["Banyak"], ["Cepat"], ["Kecil"], ["Putih"], ["Lepas"], ["Baik"], ["Pesat"], ["Senang"], ["Barunya"], ["Indah"], 
        ["Panjang"], ["Kelemahannya"], ["Terbesar"], ["Kebanggaan"], ["Setia"], ["Sejuk"], ["Tinggi"], ["Pendorong"], ["Manis"], ["Daya"], 
        ["Indah"], ["Baik"], ["Pesat"], ["Senang"], ["Barunya"], ["Indah"], ["Panjang"], ["Kelemahannya"], ["Kebanggaan"], ["Setia"], ["Sejuk"], 
        ["Tinggi"], ["Pendorong"], ["Manis"], ["Daya"], ["Terbesar"], ["Pemilik"], ["Ramai"], ["Selalu"], ["Indah"], ["Ikon"], ["Terdalam"], 
        ["Pemimpin"], ["Pakar"], ["Pembicara"], ["Indah"], ["Ramai"], ["Terbesar"], ["Baru"], ["Digunakan"], ["Pagi"], ["Besar"],
        ["Pembicara"],
        ["Adv", "AdjP"],
        ["AdjP", "Adv"],
        ["AdjP", "VP"],
        ["AdjP", "NP"],
        ["Banyak"], ["Lima"], ["Sedikit"], ["Seekor"], ["Dua"], ["Lima"], ["Belas"], ["Tiga"], ["Tujuh"], ["Puluh"], ["Sepuluh"], ["Dua"], ["Delapan"],
        ["NumP", "NP"]
    ],
    "Pel": [
        ["Di"], ["Dengan"], ["Pada"], ["Dalam"], ["Setiap"], ["Dengan"], ["Di"], ["Pada"], ["Dalam"], ["Untuk"],

        ["PP", "NP"],
        ["PP", "VP"],
        ["PP", "NumP"],
        ["PP", "AdjP"],
        ["PP", "PropNoun"],
        ["PP", "Pronoun"],
        ["Dewasa"], ["Jarang"], ["Lezat"], ["Sering"], ["Banyak"], ["Cepat"], ["Kecil"], ["Putih"], ["Lepas"], ["Baik"], ["Pesat"], ["Senang"], ["Barunya"], ["Indah"], 
        ["Panjang"], ["Kelemahannya"], ["Terbesar"], ["Kebanggaan"], ["Setia"], ["Sejuk"], ["Tinggi"], ["Pendorong"], ["Manis"], ["Daya"], 
        ["Indah"], ["Baik"], ["Pesat"], ["Senang"], ["Barunya"], ["Indah"], ["Panjang"], ["Kelemahannya"], ["Kebanggaan"], ["Setia"], ["Sejuk"], 
        ["Tinggi"], ["Pendorong"], ["Manis"], ["Daya"], ["Terbesar"], ["Pemilik"], ["Ramai"], ["Selalu"], ["Indah"], ["Ikon"], ["Terdalam"], 
        ["Pemimpin"], ["Pakar"], ["Pembicara"], ["Indah"], ["Ramai"], ["Terbesar"], ["Baru"], ["Digunakan"], ["Besar"],
        ["Adv", "AdjP"],
        ["AdjP", "Adv"],
        ["AdjP", "VP"],
        ["AdjP", "NP"]
    ],
    "Ket": [
        ["Di"], ["Dengan"], ["Pada"], ["Dalam"], ["Setiap"], ["Dengan"], ["Di"], ["Pada"], ["Dalam"], ["Untuk"],

        ["PP", "NP"],
        ["PP", "VP"],
        ["PP", "NumP"],
        ["PP", "AdjP"],
        ["PP", "PropNoun"],
        ["PP", "Pronoun"],
        # ["Verb"],
        ["Verb", "NP"],
        ["Verb", "AdjP"],
        ["Adv", "VP"],
        ["Dewasa"], ["Jarang"], ["Lezat"], ["Sering"], ["Banyak"], ["Cepat"], ["Kecil"], ["Putih"], ["Lepas"], ["Baik"], ["Pesat"], ["Senang"], ["Barunya"], ["Indah"], 
        ["Panjang"], ["Kelemahannya"], ["Terbesar"], ["Kebanggaan"], ["Setia"], ["Sejuk"], ["Tinggi"], ["Pendorong"], ["Manis"], ["Daya"], 
        ["Indah"], ["Baik"], ["Pesat"], ["Senang"], ["Barunya"], ["Indah"], ["Panjang"], ["Kelemahannya"], ["Kebanggaan"], ["Setia"], ["Sejuk"], 
        ["Tinggi"], ["Pendorong"], ["Manis"], ["Daya"], ["Terbesar"], ["Pemilik"], ["Ramai"], ["Selalu"], ["Indah"], ["Ikon"], ["Terdalam"], 
        ["Pemimpin"], ["Pakar"], ["Pembicara"], ["Indah"], ["Ramai"], ["Terbesar"], ["Baru"], ["Digunakan"], ["Pagi"], ["Besar"],
        ["Adv", "AdjP"],
        ["AdjP", "Adv"],
        ["AdjP", "VP"],
        ["AdjP", "NP"]
    ],
    "NP": [
        ["Nenek"], ["Polisi"], ["Ibu"], ["Daun"], ["Ubi"], ["Acara"], ["Orang"], ["Pemadam"], ["Kebakaran"], ["Waktu"], ["Penduduk"], ["Desa"], ["Anak"], ["Laki-laki"],
        ["Makanan"], ["Siswa"], ["Taman"], ["Kota"], ["Perpustakaan"], ["Kampus"], ["Jalan"], ["Wahana"], ["Burung"], ["Merpati"],
        ["Siang"], ["Hari"], ["Kolam"], ["Kuda"], ["Lintasan"], ["Pacu"], ["Monyet"], ["Ranting"], ["Pohon"], ["Kelinci"], ["Kebun"],
        ["Lumba-lumba"], ["Bunga"], ["Padang"], ["Rumput"], ["Lebah"], ["Buaya"], ["Tepi"], ["Danau"], ["Mahasiswa"], ["Acara"], ["Seminar"],
        ["Kakek"], ["Kursi"], ["Rotan"], ["Pelatih"], ["Orang"], ["Rencana"], ["Perjalanan"], ["Pengembangan"], ["Teknologi"], ["Gadis"],
        ["Kecil"], ["Boneka"], ["Air"], ["Terjun"], ["Pegunungan"], ["Pertunjukan"], ["Seni"], ["Malam"], ["Sejarah"], ["Mekar"], ["Tua"],
        ["Rasa"], ["Cokelat"], ["Taman"], ["Kucing"], ["Teman"], ["Anak-Anak"], ["Udara"], ["Kesejukan"], ["Kesegaran"], ["Pikiran"], ["Prestasi"],
        ["Pohon"], ["Air"], ["Hujan"], ["Suasana"], ["Romantis"], ["Cita-cita"], ["Kesuksesan"], ["Hewan"], ["Peliharaan"], ["Pameran"],
        ["Karya"], ["Budaya"], ["Lokal"], ["Wisata"], ["Daerah"], ["Arab"], ["Kuliah"], ["Pentas"], ["Universitas"], ["Ogoh-ogoh"], ["Negara"],
        ["Penghasil"], ["Minyak"], ["Tahun"], ["Baru"], ["Saka"], ["Dunia"], ["Negara"], ["Pantai"], ["Bu"], ["Warung"], ["Hari"], ["Budaya"],
        ["Juara"], ["Lomba"], ["Tengah"], ["Bapak"], ["Hujan"], ["Tetangga"], ["Keindahan"], ["Pantainya"], ["Tetangga"], ["Bukit"], ["Pemandangan"],
        ["Alam"], ["Pantai"], ["Kota"], ["Danau"], ["Laut"], ["Kulinernya"], ["Bukit"], ["Tinggi"], ["Proyek"], ["Bidang"], ["Ekologi"], ["Seminar"],
        ["Dunia"], ["Keindahan"], ["Pantainya"], ["Kota"], ["Kulinernya"], ["Hujan"], ["Tengah"], ["Budaya"], ["Malam"], ["Hari"], ["Pentas"],
        ["Ogoh-ogoh"], ["Tahun"], ["Penghasil"], ["Minyak"], ["Kegiatan"], ["Pengabdian"], ["Ketertiban"], ["Ikan"], ["Kupu-kupu"], ["Sapi"], ["Nektar"],
        ["Kepulauan"], ["Pasang"], ["Sepatu"], ["Rak"], ["Buah"], ["Rumah"], ["Tahap"], ["Konstruksi"], ["Ekor"], ["Belakang"], ["Pengunjung"], ["Kamar"], ["Tidur"],
        ["Teater"], ["Mobil"], ["Kotak"], ["Mainan"], ["Buku"], ["Bungkus"], ["Rokok"], ["Kebudayaan"], ["Asrama"], ["Putri"], ["Pemain"], ["Sepak"], ["Bola"], ["Guru"], ["Tari"],

        ["NP", "Noun"],
        ["NP", "Verb"],
        ["NP", "NumP"],
        ["NP", "AdjP"],
        ["NP", "PropNoun"],
        ["NP", "Pronoun"],
        ["Adv", "NP"],
        ["Noun"],
        ["Para"], ["Itu"], ["Tersebut"], ["Dari"], ["Saya"], ["Kita"], ["Itu"], ["Ini"], ["Yang"], ["Bahasa"], ["Saya"], ["Dia"],


        ["Hitam"], ["Rindang"], ["Kontemporer"], ["Siti"], ["Rahayu"], ["Adi"], ["Santoso"], ["Ratna"], ["Kopi"], ["Denpasar"], 
        ["Kiki"], ["Prof"], ["Dr"], ["Hadi"], ["Prayitno"], ["Bali"], ["Jakarta"], ["Haryono"], ["Bogor"], ["Bandung"], ["Monas"], 
        ["Copacabana"], ["Rio"], ["de"], ["Janeiro"], ["Baikal"], ["Sinta"], ["Mediterania"], ["Bukit"], ["Tinggi"], ["Danau"], ["Baikal"], 
        ["Jawa"], ["Timur"], ["Saka"], ["Arab"], ["Saudi"], ["Indonesia"], ["Koi"], ["Jepang"], ["Medan"]
    ],
    "VP": [
        ["Menaiki"], ["Mempunyai"], ["Bermain"], ["Belajar"], ["Menjaga"], ["Terbang"], ["Berenang"], ["Pacuan"], ["Berlari"], 
        ["Bergelantungan"], ["Hinggap"], ["Mengunyah"], ["Berjemur"], ["Menjadi"], ["Menyukai"], ["Disusun"], ["Berlangsung"], ["Menghibur"], 
        ["Menjadi"], ["Memberikan"], ["Membuat"], ["Menampilkan"], ["Tarik"], ["Berlibur"], ["Merupakan"], ["Tersebut"], ["Menyanyi"], 
        ["Membantu"], ["Terpajang"], ["Adalah"], ["Luas"], ["Kursus"], ["Meneliti"], ["Orang"], ["Membeli"], ["Berlari"], ["Banyak"], 
        ["Disiram"], ["Lama"], ["Indah"], ["Nyaman"], ["Dalam"], ["Belajar"], ["Bermain"], ["Dalam"], ["Menyukai"], ["Disusun"], 
        ["Berlangsung"], ["Menghibur"], ["Menjadi"], ["Memberikan"], ["Membuat"], ["Menampilkan"], ["Tarik"], ["Merupakan"], ["Memberikan"], 
        ["Dilakukan"], ["Sedang"], ["Berlibur"], ["Merupakan"], ["Menyambut"], ["Merupakan"], ["Memiliki"], ["Terletak"], ["Menyanyi"], 
        ["Membantu"], ["Dikenal"], ["Terkenal"], ["Membantu"], ["Menjadi"], ["Terkenal"], ["Adalah"], ["Terdalam"], ["Terkenal"], ["Dikenal"], 
        ["Terletak"], ["Menyambut"], ["Terpajang"], ["Mengambil"], ["Menghadiri"], ["Mengikuti"], ["Diperbolehkan"], ["Menyelamatkan"], ["Memasak"],
        ["Melompat-lompat"], ["Mengumpulkan"],
        ["Verb", "AdjP"],
        ["Adv", "VP"]
    ],
    "AdjP": [
        ["Tinggi"], ["Bijaksana"], ["Kaya"], ["Rajin"], ["Lezat"], ["Cantik"], ["Serius"],
        ["Tampan"], ["Pandai"], ["Nikmat"], ["Cepat"], ["Pintar"], ["Tambahan"], ["Harian"],
        ["Malam"], ["Memukau"], ["Lelah"], ["Baik"], ["Pesat"], ["Senang"],
        ["Barunya"], ["Indah"], ["Panjang"], ["Kelemahannya"], ["Kebanggaan"], ["Setia"],
        ["Sejuk"], ["Tinggi"], ["Pendorong"], ["Manis"], ["Daya"], ["Terbesar"], ["Pemilik"],
        ["Ramai"], ["Selalu"], ["Indah"], ["Ikon"], ["Terdalam"], ["Pemimpin"], ["Pakar"],
        ["Pembicara"], ["Digunakan"],
        ["Adv", "AdjP"],
        ["AdjP", "Adv"],
        # ["AdjP", "VP"],
        ["AdjP", "NP"]
    ],
    "NumP": [
        ["Banyak"], ["Lima"], ["Sedikit"], ["Seekor"], ["Dua"], ["Lima"], ["Belas"], ["Tiga"], ["Tujuh"], ["Puluh"], ["Sepuluh"], ["Dua"], ["Delapan"],
        ["NumP", "NP"],
        ["Num", "NumP"]
    ],
    "PP": [
        ["Di"], ["Dengan"], ["Pada"], ["Dalam"], ["Setiap"], ["Dengan"], ["Di"], ["Pada"], ["Dalam"], ["Untuk"],

        ["PP", "NP"],
        ["PP", "VP"],
        ["PP", "NumP"],
        ["PP", "AdjP"],
        ["PP", "PropNoun"],
        ["PP", "Pronoun"],
        ["Prep"]
    ],
    "X": [["S", "P"]],
    "Y": [["O", "Pel"]],
    "Z": [["O", "Ket"]],
    "A": [["Y", "Ket"]],
    "Noun": [
        ["Nenek"], ["Polisi"], ["Ibu"], ["Daun"], ["Ubi"], ["Acara"], ["Orang"], ["Pemadam"], ["Kebakaran"], ["Waktu"], ["Penduduk"], ["Desa"], ["Anak"], ["Laki-laki"],
        ["Makanan"], ["Siswa"], ["Taman"], ["Kota"], ["Perpustakaan"], ["Kampus"], ["Jalan"], ["Wahana"], ["Burung"], ["Merpati"],
        ["Siang"], ["Hari"], ["Kolam"], ["Kuda"], ["Lintasan"], ["Pacu"], ["Monyet"], ["Ranting"], ["Pohon"], ["Kelinci"], ["Kebun"],
        ["Lumba-lumba"], ["Bunga"], ["Padang"], ["Rumput"], ["Lebah"], ["Buaya"], ["Tepi"], ["Danau"], ["Mahasiswa"], ["Acara"], ["Seminar"],
        ["Kakek"], ["Kursi"], ["Rotan"], ["Pelatih"], ["Orang"], ["Rencana"], ["Perjalanan"], ["Pengembangan"], ["Teknologi"], ["Gadis"],
        ["Kecil"], ["Boneka"], ["Air"], ["Terjun"], ["Pegunungan"], ["Pertunjukan"], ["Seni"], ["Malam"], ["Sejarah"], ["Mekar"], ["Tua"],
        ["Rasa"], ["Coklat"], ["Taman"], ["Kucing"], ["Teman"], ["Anak-Anak"], ["Udara"], ["Kesejukan"], ["Kesegaran"], ["Pikiran"], ["Prestasi"],
        ["Pohon"], ["Air"], ["Hujan"], ["Suasana"], ["Romantis"], ["Cita-cita"], ["Kesuksesan"], ["Hewan"], ["Peliharaan"], ["Pameran"],
        ["Karya"], ["Budaya"], ["Lokal"], ["Wisata"], ["Daerah"], ["Arab"], ["Kuliah"], ["Pentas"], ["Universitas"], ["Ogoh-ogoh"], ["Negara"],
        ["Penghasil"], ["Minyak"], ["Tahun"], ["Baru"], ["Saka"], ["Dunia"], ["Negara"], ["Pantai"], ["Bu"], ["Warung"], ["Hari"], ["Budaya"],
        ["Juara"], ["Lomba"], ["Tengah"], ["Bapak"], ["Hujan"], ["Tetangga"], ["Keindahan"], ["Pantainya"], ["Tetangga"], ["Bukit"], ["Pemandangan"],
        ["Alam"], ["Pantai"], ["Kota"], ["Danau"], ["Laut"], ["Kulinernya"], ["Bukit"], ["Tinggi"], ["Proyek"], ["Bidang"], ["Ekologi"], ["Seminar"],
        ["Dunia"], ["Keindahan"], ["Pantainya"], ["Kota"], ["Kulinernya"], ["Hujan"], ["Tengah"], ["Budaya"], ["Malam"], ["Hari"], ["Pentas"],
        ["Ogoh-ogoh"], ["Tahun"], ["Penghasil"], ["Minyak"], ["Kegiatan"], ["Pengabdian"], ["Ketertiban"], ["Ikan"], ["Kupu-kupu"], ["Sapi"], ["Nektar"],
        ["Kepulauan"], ["Pasang"], ["Sepatu"], ["Rak"], ["Buah"], ["Rumah"], ["Tahap"], ["Konstruksi"], ["Ekor"], ["Belakang"], ["Pengunjung"], ["Kamar"], ["Tidur"],
        ["Teater"], ["Mobil"], ["Kotak"], ["Mainan"], ["Buku"], ["Bungkus"], ["Rokok"], ["Kebudayaan"], ["Asrama"], ["Putri"], ["Pemain"], ["Sepak"], ["Bola"], ["Guru"], ["Tari"],

    ],
    "Pronoun": [
        ["Para"], ["Itu"], ["Tersebut"], ["Dari"], ["Saya"], ["Kita"], ["Itu"], ["Ini"], ["Yang"], ["Bahasa"], ["Saya"], ["Dia"],

    ],
    "PropNoun": [
        
        ["Hitam"], ["Rindang"], ["Kontemporer"], ["Siti"], ["Rahayu"], ["Adi"], ["Santoso"], ["Ratna"], ["Kopi"], ["Denpasar"], 
        ["Kiki"], ["Prof"], ["Dr"], ["Hadi"], ["Prayitno"], ["Bali"], ["Jakarta"], ["Haryono"], ["Bogor"], ["Bandung"], ["Monas"], 
        ["Copacabana"], ["Rio"], ["de"], ["Janeiro"], ["Baikal"], ["Sinta"], ["Mediterania"], ["Bukit"], ["Tinggi"], ["Danau"], ["Baikal"], 
        ["Jawa"], ["Timur"], ["Saka"], ["Arab"], ["Saudi"], ["Indonesia"], ["Koi"], ["Jepang"], ["Medan"]
    ],
    "Adj": [
        ["Dewasa"], ["Jarang"], ["Lezat"], ["Sering"], ["Banyak"], ["Cepat"], ["Kecil"], ["Putih"], ["Lepas"], ["Baik"], ["Pesat"], ["Senang"], ["Barunya"], ["Indah"], 
        ["Panjang"], ["Kelemahannya"], ["Terbesar"], ["Kebanggaan"], ["Setia"], ["Sejuk"], ["Tinggi"], ["Pendorong"], ["Manis"], ["Daya"], 
        ["Indah"], ["Baik"], ["Pesat"], ["Senang"], ["Barunya"], ["Indah"], ["Panjang"], ["Kelemahannya"], ["Kebanggaan"], ["Setia"], ["Sejuk"], 
        ["Tinggi"], ["Pendorong"], ["Manis"], ["Daya"], ["Terbesar"], ["Pemilik"], ["Ramai"], ["Selalu"], ["Indah"], ["Ikon"], ["Terdalam"], 
        ["Pemimpin"], ["Pakar"], ["Pembicara"], ["Indah"], ["Ramai"], ["Terbesar"], ["Baru"], ["Digunakan"], ["Pagi"], ["Besar"],
    ],
    "Verb": [
        ["Menaiki"], ["Mempunyai"], ["Bermain"], ["Belajar"], ["Menjaga"], ["Terbang"], ["Berenang"], ["Pacuan"], ["Berlari"], 
        ["Bergelantungan"], ["Hinggap"], ["Mengunyah"], ["Berjemur"], ["Menjadi"], ["Menyukai"], ["Disusun"], ["Berlangsung"], ["Menghibur"], 
        ["Menjadi"], ["Memberikan"], ["Membuat"], ["Menampilkan"], ["Tarik"], ["Berlibur"], ["Merupakan"], ["Tersebut"], ["Menyanyi"], 
        ["Membantu"], ["Terpajang"], ["Adalah"], ["Luas"], ["Kursus"], ["Meneliti"], ["Orang"], ["Membeli"], ["Berlari"], ["Banyak"], 
        ["Disiram"], ["Lama"], ["Indah"], ["Nyaman"], ["Dalam"], ["Belajar"], ["Bermain"], ["Dalam"], ["Menyukai"], ["Disusun"], 
        ["Berlangsung"], ["Menghibur"], ["Menjadi"], ["Memberikan"], ["Membuat"], ["Menampilkan"], ["Tarik"], ["Merupakan"], ["Memberikan"], 
        ["Dilakukan"], ["Sedang"], ["Berlibur"], ["Merupakan"], ["Menyambut"], ["Merupakan"], ["Memiliki"], ["Terletak"], ["Menyanyi"], 
        ["Membantu"], ["Dikenal"], ["Terkenal"], ["Membantu"], ["Menjadi"], ["Terkenal"], ["Adalah"], ["Terdalam"], ["Terkenal"], ["Dikenal"], 
        ["Terletak"], ["Menyambut"], ["Terpajang"], ["Mengambil"], ["Menghadiri"], ["Mengikuti"], ["Diperbolehkan"], ["Menyelamatkan"], ["Memasak"],
        ["Melompat-lompat"], ["Mengumpulkan"]
    ],
    "Adv": [
        ["Sekitar"], ["Saja"], ["Hanya"], ["Selalu"], ["Sedang"], ["Sangat"], ["Akan"], ["Berisi"], 
        ["Harus"], ["Sudah"], ["Sangat"], ["Hadir"], ["Sangat"], ["Selalu"], ["Akan"], ["Dengan"]
    ],
    "Num": [
        ["Banyak"], ["Lima"], ["Sedikit"], ["Seekor"], ["Dua"], ["Lima"], ["Belas"], ["Tiga"], ["Tujuh"], ["Puluh"], ["Sepuluh"], ["Dua"], ["Delapan"]
    ],
    "Prep": [
        ["Di"], ["Dengan"], ["Pada"], ["Dalam"], ["Setiap"], ["Dengan"], ["Di"], ["Pada"], ["Dalam"], ["Untuk"]

    ]
}